apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
  labels:
    creation_method: manual
    env: prod
spec:
  nodeselector:
    gpu: "true"
  containers:
  - name: kubia
    image: mtthwmths/kubia-c2-1-2
    ports:
    - containerPort: 8080
      protocol: TCP

