apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 1
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: mtthwmths/kubia-c2-1-2
        ports:
        - containerPort: 8080

